### PR TITLE
Qualified type operator exports

### LINKED ISSUE #191: Qualified infix type operator in export list causes issues
In `GHC.TypeLits` we see

```haskell

module GHC.TypeLits
  ( -- ...
  , type (N.<=), type (N.<=?), type (N.+), type (N.*), type (N.^), type (N.-)
  , type N.Div, type N.Mod, type N.Log2
  -- ...

  ) where
```

The qualification of the symbolic operators causes an issue:

ghc-typelits-issue

### PR DESCRIPTION
**Pull request by mixphix**
Fixes #191.

### CODE REVIEW

**Comment by sheaf** [comment]
Thank you so much, that's a great fix.

Could you:
  - add a test case for `type (Qualified.T)`,
  - squash the commits?

Then we should be good to go!

**Comment by mixphix** [comment]
An issue with `MagicHash` caught me by surprise in the (now fixed, thanks!) tests. I threw `reserved_symbol` into the includes and now everything works again! :)

**Comment by sheaf** [comment]
Rebase needed, otherwise this is good to go. Thanks a lot!

Does your patch now also fix the following issue (that I found out after you mentioned MagicHash)?

```haskell
module M
  ( T#(f#,C#,(+#)) )
  where
```

The `(+#)` currently throws everything off.

**Comment by mixphix** [comment]
It does not. Actually, there's a number of issues remaining here, namely that I didn't notice the `where` clause has now been discoloured due to the end match. I'll have to work on this some more.

**Comment by mixphix** [comment]
> The `(+#)` currently throws everything off.

This is partly a problem with `prefix_op`, which does not allow `#` to appear at the end of such things, and partly with the hash symbol match itself, which does not register as such when immediately followed by `(`.

**Comment by mixphix** [comment]
FWIW I’ve fixed the issue with the where keyword. If the other hash stuff is already caught in a test that’s expected to fail (for now), I’ll reopen this with just the qualification patch?

**Comment by sheaf** [comment]
Yes that's good with me, I'll make a separate "expect fail" test for the magic hash issue. Thanks.

**Comment by mixphix** [comment]
Womp womp. Can't re-open because I force-pushed. Sorry, I'll make a new PR.

**Pull request closed without merging**
