### PR TITLE
Improvements to multiline type/data declarations

### PR DESCRIPTION
**Pull request by sheaf**
Quite a lot of changes in this one:

  - There was a really annoying bug with data declarations indentation tracking, because of the typo `(\s)*` instead of `(\s*)`, so we were capturing a single space of indentation as opposed to the whole indentation. Fixing this means indented data declarations now work properly (fixing #91 for good).
  - Data instance / newtype instance declarations are now highlighted properly (just re-use the code for data/newtype).
  - Multiline type and data declarations work a lot better now, including allowing comments. It even skips over lines which just consist of a `--` comment. This is done with the ```\s*-*--(?![\p{S}\p{P}&&[^(),;\[\]`{}_"']]).*$``` regexp. Unfortunately I can't skip over block comments because I can't do that computation in a regular expression. **Edit:** Not true as pointed out below, now block comments supported too.
  - Fixes the `=` sign not always being properly highlighted in multiline type declarations. Brought to my attention by #146 (added three test cases to completely cover the different situations).

Fixes test cases `Comments`, `Keywords`, `T0091`.

### CODE REVIEW

**Comment by sheaf** [comment]
Oops looks like I broke something with newtype declarations, working on a fix.

**Comment by JustusAdam** [comment]
Hey this looks like good work :+1: 

I think we can deal with block comments. We can add `block_comment` to the `patterns`. The `begin` from `block_comment` will match, resulting in the `block_comment` multiline match taking over from the one from `type/data`. This means so long as the block comment has not ended the `end` pattern from the outer multiline match will not trigger. Once the block comment finishes the outer match should take over again.

**Comment by sheaf** [comment]
I fixed the breakage with newtypes and I added your suggestion regarding block comments, which seems to work nicely! I didn't realise the outer match would take over again like that.

**Comment by JustusAdam** [comment]
Yeah, I don't think they even document those mechanics. I only frustratingly found out in bugs where you have to repeat the end condition because otherwise it never terminates the outer condition.

**Comment by JustusAdam** [comment]
Oh. Thanks for fixing it. :sweat_smile: I had some issues trying to get the test runner working locally

**Comment by sheaf** [comment]
The issue was that you accidentally removed the `name: meta.declaration.adt.haskell` scope, so one of the tests failed. The test output should be more readable now, so you should be able to make sense of the tests without needing to run them locally.

**Pull request merged**
