### PR TITLE
Automatically continue comments on newlines

### PR DESCRIPTION
**Pull request by bubba**
## For changes related to the grammar

- Please add a test case.
  
  - For changes to regular Haskell code simply add a new section to `test/syntax-examples/test.hs`.
    Make sure your case has a descriptive comment about what it is covering.

  - When adding foreign definitions, i.e. embeddings, add a new test file for the embedding in
    question.

- Add your changes to the `CHANGELOG.md` file, ideally with a reference to the issue the PR is
  fixing. Also feel free to credit yourself there.

### CODE REVIEW

**Comment by bubba** [comment]
I'm not sure if continuing `--` comments on newlines is desired default behaviour. If not is there a configuration option we can put this behind?

**Comment by bubba** [comment]
Completely forgot I recorded a demo of it here: https://streamable.com/zraazx

**Comment by jneira** [comment]
@JustusAdam hi, thanks for your work with the extension, do you have any feedback on the pr?
//cc @bubba

**Comment by JustusAdam** [comment]
First off thanks for adding this, I like this feature. 
Second: I'm not so much concerned about default behavior, but that the current behavior is different and that people may be irritated by the fact that it changes. So ideally I would like this to be a configuration option.

**Pull request closed without merging**
