### PR TITLE
Add unit testing with vscode-tmgrammar-test

### PR DESCRIPTION
**Pull request by sheaf**
To automate testing (to help against regressions and to avoid having to manually look through the test files to gauge whether the highlighting is correct), I have gone through the past issues on this repository to write tests which make use of the [`vscode-tmgrammar-test`](https://github.com/PanAeon/vscode-tmgrammar-test) package, which you should be able to install with [`node`](https://www.npmjs.com/package/vscode-tmgrammar-test).    

Once `vscode-tmgrammar-test` is installed and available in the command line, to run a test, input the command:

```bash
vscode-tmgrammar-test -s source.haskell -g "path/to/haskell.json" -t "path/to/testfile"
```

To write the tests, it can be helpful to use the snapshot functionality: replacing `vscode-tmgrammar-test` with `vscode-tmgrammar-snap` in the above command will generate a snapshot file which contains all the TextMate scopes generated by the grammar. You can then cherry pick the relevant/correct annotations and use them to create a test case (this is how I created most of the tests).    

You can also run all tests at once with the command
```bash
vscode-tmgrammar-test -s source.haskell -g "path/to/haskell.json" -t "path-to-repo-root/test/*/*.hs"
```
You can pass the flag `-c` for a condensed output (but this will still output a lot of information for failing test cases).    

The next step is to have a continuous integration pipeline which runs these tests. Some of the tests don't pass currently, so there should be a way of marking some tests as `expect-broken` for the time being. I'm not sure what's the best way to set up CI is for this situation (and I can't say I really fancy writing a bunch of JavaScript to manage the tests).

### CODE REVIEW

**Comment by sheaf** [comment]
I've added a bash script which runs all the tests.    
The script contains a list of all the tests that are expected broken. For the moment I've just included all the tests that are currently broken.

**Comment by sheaf** [comment]
I've now added GitHub CI which runs the tests.

**Comment by JustusAdam** [comment]
Amazing, that is super useful. I had no idea a test harness for tm grammars for vscode existed.

**Comment by sheaf** [comment]
You can see the result of the tests in the `Actions` pane of the repository on GitHub. For instance this merge created [this test log](https://github.com/JustusAdam/language-haskell/runs/630284658) (click on the `Run tests` tasks for the info).

**Pull request merged**
