### PR TITLE
Fixed issue #21.

### PR DESCRIPTION
**Pull request by lemourin**
Brought back src/extension.ts file, removed "decreaseIndentPattern"
from it because it does more bad than good.

### CODE REVIEW

**Comment by metaleap** [comment]
No need for the "new" .ts file if you just remove decreaseIndentPattern from the .json: as per the diffs the other pattern seems exactly the same side-by-side (other than string syntax in the .json version), to wit:

    ts:		/((\b(if\b.*|then|else|do|of|let|in|where))|=|->|>>=|>=>|=<<|(^(data)( |\t)+(\w|')+( |\t)*))( |\t)*$/
    json:	((\b(if\b.*|then|else|do|of|let|in|where))|=|->|>>=|>=>|=<<|(^(data)( |\t)+(\w|')+( |\t)*))( |\t)*$/

(Quotes/escs removed from latter)

**Comment by lemourin** [comment]
Well, as i said in the issue's description (#21), vscode doesn't look at all at the json's field "indentationRules" which is why it has to be set by the .ts script.

**Comment by metaleap** [comment]
Ah really? Sounds like a bug to be reported to vscode repo then  =)  unless the field has been deprecated or mispelled somewhere..

**Comment by JustusAdam** [comment]
@metaleap I understand that. I have at least one weird indent pattern myself. I will indent everything with 4 spaces except `where` (the keyword not the block). And as a result indent detect will more often than not detect the whole as 2 spaces, which is annoying.

Anyways I agree with the removal of "decreaseIndent" but I think we should keep "increaseIndent", It does make sense in many cases and I think it encourages a good style for the most part.

**Comment by JustusAdam** [comment]
It would be nice to have a config option to turn the auto indent off maybe ... the trouble is I have no idea how to define and use config options in vscode.

**Comment by metaleap** [comment]
Oooh! Now *there's* an idea, it's coming from a .ts now so we can make it config'able. Will wire up a PR later today for this, it's in my own interest

**Comment by metaleap** [comment]
Well once *this* patch above is accepted into the current main branch

**Pull request merged**
