### PR TITLE
Unit type applications

### LINKED ISSUE #225: Bare unit-type applications not respected
Bare applications of the unit type `()` are not properly highlighted, as shown below:

Type applications showing a nested unit type application highlighted, but the outer brackets remain unhighlighted, even with no contents

### PR DESCRIPTION
**Pull request by mixphix**
Fixes #225.

### CODE REVIEW

**Comment by mixphix** [comment]
```hs
❯ ghci 
GHCi, version 9.2.7: https://www.haskell.org/ghc/  :? for help
ghci> :t ( )
( ) :: ()
```

Wow, TIL!

**Comment by mixphix** [comment]
Considering no part of the syntax highlighting currently recognizes it, I’d rather leave that as a separate issue. I’ll squash the commits though!

**Comment by mixphix** [comment]
And of course, the previous comment was based on the GitHub highlighter, not the VS Code one. I'll force-push again with the appropriate patch and test case.

**Comment by sheaf** [comment]
Perfect, thanks a lot!

**Pull request merged**
