### PR TITLE
Continuing comments (configurable)

### PR DESCRIPTION
**Pull request by jneira**
* Continues #174 with the aim of make configurable the behaviour added there, as suggested in https://github.com/JustusAdam/language-haskell/pull/174#issuecomment-813325599

### CODE REVIEW

**Comment by jneira** [comment]
I am working on this again and i found that to have to remove the `--` for the last comment line is quite disturbing.
What about if we delete the comment line if we do a new line wit no content?
So pressing enter (`|` is the cursor position)

```
-- first line
-- last line
-- |
```

will result in

```
-- first line
-- last line

|
```

**Comment by jneira** [comment]
@JustusAdam hi! i think this is ready to review, once i've make it configurable (true by default), thanks!

**Comment by jneira** [comment]
@JustusAdam hi again! would this pr need some change? thanks!

**Comment by sheaf** [comment]
Hi Javier. My apologies for the lack of response on this, I'm not too familiar with this aspect of things.

I've just given this is a try, and I think it works quite well for `--` comments. I'm still not sure what behaviour we want to use for ending these multiline comments, because I certainly often write comments of the form

```haskell
-- blah blah blah
-- blah blah blah
--
-- more stuff, blah blah blah
-- blah blah
```

and I think it would be irritating if it automatically removed the comment on the next line. So the current behaviour seems OK.

Is it possible to set it up so that, for instance, "shift + enter" continues the comment, and "enter" alone does not? At least that would be what I would prefer personally, but I don't want to enforce anything on anyone.


On the other hand, for block comments I haven't noticed any change in behaviour. Could you explain what is supposed to happen now?

I apologise again for the delays, rest assured I'll endeavour to stay responsive from now on.

**Comment by sheaf** [comment]
Ah, I see, I had "editor.autoClosingBrackets" set to "never". After enabling it, it properly matches opening and closing block comments. What's the bit about the indentation?

**Comment by sheaf** [comment]
It also seems a shame that the action that automatically creates closing `-}` doesn't work as expected when text is already selected. Suppose one has something selected, like "expression" in the following example:

```haskell
blah blah blah expression blah blah
```

typing in `{` with that selection results in:

```haskell
blah blah blah {expression} blah blah
```

However, if we follow that up by typing `-` then instead of commenting out `expression` we get:

```haskell
blah blah blah {-} blah blah
```

I don't know whether it's feasible to fix this or not; I just thought it might be worth bringing up.

**Comment by sheaf** [comment]
Yet another thing I've noticed. When writing a comment over multiple lines, such as haddocks:

```haskell
-- | Start of the comment.
-- 
-- Additional info.
```

We end up with one extra space of trailing whitespace on the blank comment line. It would be nice if this extra space was removed when going to the next line.

**Comment by sheaf** [comment]
By the way @jneira, I don't mean to be discouraging with all these comments. I'm finding the feature quite useful already, so I'm definitely happy to merge something basic now (as long as it is optional, which it is) and improve on it later. Let me know what you want to do.

**Comment by jneira** [comment]
> By the way @jneira, I don't mean to be discouraging with all these comments. I'm finding the feature quite useful already, so I'm definitely happy to merge something basic now and improve on it later. Let me know what you want to do.

No worries and thanks for your thoroughful considerations, i tend to agree with all of them but i am afraid i am not an expert in vs code syntax extensions. Changes has to follow some syntax extension rules ans dont know where are the limits, tbh.
 To do a summary:

> Is it possible to set it up so that, for instance, "shift + enter" continues the comment, and "enter" alone does not? At least that would be what I would prefer personally, but I don't want to enforce anything on anyone.

It would be nice, not sure if possible

> Shouldn't that be indented one further space perhaps, if we want it to keep text aligned

Yeah and i think it should be not difficult

> the action that automatically creates closing -} doesn't work as expected when text is already selected.

Your alternative seems sensible to me, not sure if it is possible neither.

> We end up with one extra space of trailing whitespace on the blank comment line. It would be nice if this extra space was removed when going to the next line.

Also agree, i think that would be possible too.

So i will try to apply the changes i think are relatively easy and investigate the other ones.

**Comment by sheaf** [comment]
It would also be nice if the "auto close" for block comments also worked with PRAGMAS, i.e. one should be able to type `{-#` and get the corresponding closing token automatically. Currently we get `-}` but not `#-}`.

**Comment by jneira** [comment]
dont have time to continue working on this, feel free to reuse it

**Pull request closed without merging**
